-- DropForeignKey
ALTER TABLE "COMMENT" DROP CONSTRAINT "COMMENT_task_id_fkey";

-- DropForeignKey
ALTER TABLE "COMMENT" DROP CONSTRAINT "COMMENT_user_id_fkey";

-- DropForeignKey
ALTER TABLE "TASK" DROP CONSTRAINT "TASK_user_id_fkey";

-- AlterTable
ALTER TABLE "COMMENT" ALTER COLUMN "user_id" DROP NOT NULL;

-- AlterTable
ALTER TABLE "TASK" ALTER COLUMN "user_id" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "TASK" ADD CONSTRAINT "TASK_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USERS"("email") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "COMMENT" ADD CONSTRAINT "COMMENT_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USERS"("email") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "COMMENT" ADD CONSTRAINT "COMMENT_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "TASK"("id") ON DELETE CASCADE ON UPDATE CASCADE;
