-- DropForeignKey
ALTER TABLE "COMMENT" DROP CONSTRAINT "COMMENT_project_id_fkey";

-- DropForeignKey
ALTER TABLE "TASK" DROP CONSTRAINT "TASK_project_id_fkey";

-- AddForeignKey
ALTER TABLE "TASK" ADD CONSTRAINT "TASK_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "PROJECT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "COMMENT" ADD CONSTRAINT "COMMENT_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "PROJECT"("id") ON DELETE CASCADE ON UPDATE CASCADE;
